services:
  testrunner:
    image: $DEV_IMAGE_TAG
    environment:
      WORK_DIR: $PWD
      POSTGRES_HOST: cs_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customer_storage
    build:
      dockerfile: Dockerfile.dev
      context: .
      args:
        OTP_VERSION: $OTP_VERSION
        THRIFT_VERSION: $THRIFT_VERSION
        ELP_VERSION: $ELP_VERSION
        ELP_OTP_VERSION: $ELP_OTP_VERSION
    volumes:
      - .:$PWD
    hostname: cs.default
    depends_on:
      cs_db:
        condition: service_healthy
    working_dir: $PWD

  cs_db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customer_storage
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
